name: CD

on:
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:
    inputs:
      image:
        required: true
        description: 'Enter image repository'
        default: '5upreme/flask'
      tag:
        required: true
        description: 'Enter image tag'
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SCM
        uses: actions/checkout@v4

      - name: Login to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Select GCP project
        run: gcloud config set project studied-limiter-459823-r2

      - name: Install plugin
        run: gcloud components install kubectl gke-gcloud-auth-plugin

      - name: Connect to Kubernetes
        run: gcloud container clusters get-credentials cluster-1 --region us-central1 --project studied-limiter-459823-r2

      - name: Install app
        run: helm upgrade --install flask ./flask --set deployment.image.repository=${{ inputs.image }} --set deployment.image.tag=${{ inputs.tag }}